# Default initial positions for g1_29dof_with_hand's ros2_control fake system

initial_positions:
  left_shoulder_pitch_joint: 0.2906
  left_elbow_joint: 0.9779
  left_shoulder_roll_joint: 0.3178
  left_shoulder_yaw_joint: -0.0157
  left_wrist_pitch_joint: -0.0855
  left_wrist_roll_joint: 0.1855
  left_wrist_yaw_joint: 0.0304
  right_shoulder_pitch_joint: 0.2836
  right_elbow_joint: 0.9851
  right_shoulder_roll_joint: -0.3151
  right_shoulder_yaw_joint: 0.0182
  right_wrist_pitch_joint: 0.0593
  right_wrist_roll_joint: -0.2342
  right_wrist_yaw_joint: -0.0431
  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0
