# Default initial positions for g1_29dof_with_hand's ros2_control fake system

initial_positions:
  left_shoulder_pitch_joint: 0.0
  left_elbow_joint: 0.0
  left_shoulder_roll_joint: 0.0
  left_shoulder_yaw_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_roll_joint: 0.0
  left_wrist_yaw_joint: 0.0
  right_shoulder_pitch_joint: 0.0
  right_elbow_joint: 0.0
  right_shoulder_roll_joint: 0.0
  right_shoulder_yaw_joint: 0.0
  right_wrist_pitch_joint: 0.0
  right_wrist_roll_joint: 0.0
  right_wrist_yaw_joint: 0.0

  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0
