# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 如果连接真机器人，joint_state_broadcaster注释掉（这个控制器会往joint_states发布数据）


left_arm_group_controller:
  ros__parameters:
    joints:
      # - waist_yaw_joint
      # - waist_roll_joint
      # - waist_pitch_joint
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    fake_sensor_commands: true
right_arm_group_controller:
  ros__parameters:
    joints:
      # - waist_yaw_joint
      # - waist_roll_joint
      # - waist_pitch_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    fake_sensor_commands: true